server:
  port: 8084
  
spring:
  data:
    mongodb:
      database: microservices
      uri: mongodb://localhost:27017
  application:
     name: RATING-SERVICE  
  config:
    import: optional:configserver:http://localhost:8086
    
okta:
  oauth2:
    issuer: https://dev-13111056.okta.com/oauth2/default
    audience: api://default  
         